### ISSUE TITLE
Wrong params order on ga.send function

### ISSUE THREAD

**Issue by carmelhm** [Ebury/huha#2]
On the method `sendToGoogleAnalytics()` the function used to send the payload to GA is using params in an incorrect order according to the API spec .

Current function usage:

`ga('send', 'event', this.action, this.section, this.object, this.value);
`

According with the [API doc](https://developers.google.com/analytics/devguides/collection/analyticsjs/events
) the order of the params should be: 
`ga('send', 'event', [eventCategory], [eventAction], [eventLabel], [eventValue], [fieldsObject]);`

Considering that `this.action` means the action of the event, and `this.section` is the category, the correct call to that function should be

`ga('send', 'event', this.section, this.action, this.object, this.value);
`

**Comment by mmtr** [comment]
Thanks for reporting! Fix is ready in #3
